### PR TITLE
[WIP] Establish communication standards

### PR DESCRIPTION
**Pull request by jbmagination**
Right now, this is just a base for terminology. There are also no terms listed. I have a few ideas though, and I imagine there are more things we can clarify over time (e.g. if you use a canned response / template response, it should be disclosed that it's canned / a template.)

### CODE REVIEW

**Review by sudocode1 — APPROVED** [review]
LGTM. We can update later.

**Comment by jbmagination** [comment]
Not yet. I was hoping we could use this PR to discuss terms / what communication standards are implemented.

**Comment by jbmagination** [comment]
Now that we have Nextcloud, can we discuss this there?

**Comment by jbmagination** [comment]
Still need to do this-- since the Nextcloud website is also down, discussion here would be okay. Should probably be transparent about it anyways since we're going through the effort of making this documentation public.

**Pull request merged**
