### PR TITLE
Use The Unlicense for LICENSE

### PR DESCRIPTION
**Pull request by sudocode1**
This would fit in pretty well with the aims of the repo. https://choosealicense.com/licenses/unlicense/

### CODE REVIEW

**Comment by jbmagination** [comment]
As our code of conduct policy is under its own license (MIT/Expat), this probably won't work. 

I went with the [FSFAP](https://fedoraproject.org/wiki/Licensing/FSFAP) instead so I could get rid of the license files and keep the one file for the code of conduct, which makes it clear and obvious that it's for *that file only* being in its own folder. The code of conduct is the sole exception.

**Comment by sudocode1** [comment]
This would not be a global license. This would be applied to anything that doesn't have it's own license.

**Comment by jbmagination** [comment]
That's not directly obvious with putting `LICENSE` at the root. I think we'd be better off just doing a license per folder-- we can adapt as needed for each project.

And even then, considering most of the stuff that would be in here is probably software / one-offs, Apache License would work better IMO.

**Comment by sudocode1** [comment]
Yeah okay.

**Pull request closed without merging**
